### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by dza6549** [rupeshs/SDImageGenerator#2]
Hi there\
SDIG was working fine last night. I downloaded 1.5 and produced images. I shut down my computer. This morning I am getting this error. Can you please advise? Thank you.

`07/10/2022 08:06:33 "  File \"D:\\SDImageGenerator-1.0.5-portable-x64\\SDImageGenerator-1.0.5-portable-x64\\sdenv\\mf\\envs\\sdimgenv\\lib\\site-packages\\torch\\serialization.py\", line 997, in load_tensor"

07/10/2022 08:06:33 "    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()"

07/10/2022 08:06:33 "PermissionError: [Errno 13] Permission denied"

07/10/2022 08:06:33 procFinished

07/10/2022 08:06:33 procFinished: Bytes available: 0

07/10/2022 08:06:33 exit_code: 1 exit_status: QProcess::NormalExit

07/10/2022 08:06:33 Good bye`

**Comment by rupeshs** [comment]
Are you using it from the same user account? Please use it from the nonsystem drive.
